// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNAqFeubYmTnccpUcg6HRbQB8VtvQpccg',
    appId: '1:322307588118:web:6f36784e6c9744c0e43537',
    messagingSenderId: '322307588118',
    projectId: 'alphago-544c7',
    authDomain: 'alphago-544c7.firebaseapp.com',
    databaseURL:
        'https://alphago-544c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphago-544c7.appspot.com',
    measurementId: 'G-B6ZWNX391H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL6UusT1GizqmXrIiEFrJ5b9JyJPEXDGE',
    appId: '1:322307588118:android:0e4effb9da111393e43537',
    messagingSenderId: '322307588118',
    projectId: 'alphago-544c7',
    databaseURL:
        'https://alphago-544c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphago-544c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDsjXO9OaQKP65L9f7FUAu91LCp9NBMcg',
    appId: '1:322307588118:ios:4ccfe39cc139625ee43537',
    messagingSenderId: '322307588118',
    projectId: 'alphago-544c7',
    databaseURL:
        'https://alphago-544c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphago-544c7.appspot.com',
    iosClientId:
        '322307588118-meuce5o8uu8sg2e0tjevutvogqn4a0l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDsjXO9OaQKP65L9f7FUAu91LCp9NBMcg',
    appId: '1:322307588118:ios:4ccfe39cc139625ee43537',
    messagingSenderId: '322307588118',
    projectId: 'alphago-544c7',
    databaseURL:
        'https://alphago-544c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alphago-544c7.appspot.com',
    iosClientId:
        '322307588118-meuce5o8uu8sg2e0tjevutvogqn4a0l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphago',
  );
}
